export const typography = {
	fontFamily: {
		regular: "System",
		medium: "System",
		semibold: "System",
		bold: "System",
		display: "System",
		displayMedium: "System",
		displayBold: "System",
		monospace: "monospace",
	},
	fontSize: {
		displayLarge: 57,
		displayMedium: 45,
		displaySmall: 36,
		headlineLarge: 32,
		headlineMedium: 28,
		headlineSmall: 24,
		titleLarge: 22,
		titleMedium: 16,
		titleSmall: 14,
		bodyLarge: 16,
		bodyMedium: 14,
		bodySmall: 12,
		labelLarge: 14,
		labelMedium: 12,
		labelSmall: 11,
	},
	lineHeight: {
		displayLarge: 64,
		displayMedium: 52,
		displaySmall: 44,
		headlineLarge: 40,
		headlineMedium: 36,
		headlineSmall: 32,
		titleLarge: 28,
		titleMedium: 24,
		titleSmall: 20,
		bodyLarge: 24,
		bodyMedium: 20,
		bodySmall: 16,
		labelLarge: 20,
		labelMedium: 16,
		labelSmall: 16,
	},
	text: {
		displayLarge: {
			fontFamily: "display",
			fontSize: 57,
			lineHeight: 64,
			fontWeight: "400",
		},
		displayMedium: {
			fontFamily: "display",
			fontSize: 45,
			lineHeight: 52,
			fontWeight: "400",
		},
		displaySmall: {
			fontFamily: "display",
			fontSize: 36,
			lineHeight: 44,
			fontWeight: "400",
		},
		headlineLarge: {
			fontFamily: "display",
			fontSize: 32,
			lineHeight: 40,
			fontWeight: "400",
		},
		headlineMedium: {
			fontFamily: "display",
			fontSize: 28,
			lineHeight: 36,
			fontWeight: "400",
		},
		headlineSmall: {
			fontFamily: "display",
			fontSize: 24,
			lineHeight: 32,
			fontWeight: "400",
		},
		titleLarge: {
			fontFamily: "displayMedium",
			fontSize: 22,
			lineHeight: 28,
			fontWeight: "500",
		},
		titleMedium: {
			fontFamily: "displayMedium",
			fontSize: 16,
			lineHeight: 24,
			fontWeight: "500",
		},
		titleSmall: {
			fontFamily: "displayMedium",
			fontSize: 14,
			lineHeight: 20,
			fontWeight: "500",
		},
		bodyLarge: {
			fontFamily: "regular",
			fontSize: 16,
			lineHeight: 24,
			fontWeight: "400",
		},
		bodyMedium: {
			fontFamily: "regular",
			fontSize: 14,
			lineHeight: 20,
			fontWeight: "400",
		},
		bodySmall: {
			fontFamily: "regular",
			fontSize: 12,
			lineHeight: 16,
			fontWeight: "400",
		},
		labelLarge: {
			fontFamily: "medium",
			fontSize: 14,
			lineHeight: 20,
			fontWeight: "500",
		},
		labelMedium: {
			fontFamily: "medium",
			fontSize: 12,
			lineHeight: 16,
			fontWeight: "500",
		},
		labelSmall: {
			fontFamily: "medium",
			fontSize: 11,
			lineHeight: 16,
			fontWeight: "500",
		},
		code: {
			fontFamily: "monospace",
			fontSize: 14,
			lineHeight: 20,
			fontWeight: "400",
		},
	},
};
export const textVariants: Record<string, any> = {
	h1: typography.text.displayLarge,
	h2: typography.text.headlineLarge,
	h3: typography.text.headlineMedium,
	body: typography.text.bodyMedium,
	caption: typography.text.bodySmall,
	button: typography.text.labelLarge,
};
