-- 1. Find all available items with owner details
SELECT i.item_id, i.title, i.daily_rate, u.name AS owner_name, u.trust_score
FROM Items i
JOIN Users u ON i.owner_id = u.user_id
WHERE i.status = 'AVAILABLE';

-- 2. View all active bookings for a specific user (as renter)
SELECT b.booking_id, i.title, b.start_date, b.end_date, b.total_price, b.status
FROM Bookings b
JOIN Items i ON b.item_id = i.item_id
WHERE b.renter_id = 3
  AND b.status IN ('APPROVED', 'PENDING');

-- View bookings that are currently in progress
SELECT b.booking_id, i.title, b.start_date, b.end_date, b.total_price, b.status
FROM Bookings b
JOIN Items i ON b.item_id = i.item_id
WHERE b.renter_id = 3
  AND b.status = 'APPROVED'
  AND CURDATE() BETWEEN b.start_date AND b.end_date;

-- 3. Calculate total revenue generated by an owner
SELECT i.owner_id, u.name, SUM(b.total_price) AS total_revenue
FROM Bookings b
JOIN Items i ON b.item_id = i.item_id
JOIN Users u ON i.owner_id = u.user_id
WHERE b.status = 'COMPLETED'
GROUP BY i.owner_id, u.name;

-- 4. Find all users with a trust score below 90
SELECT student_id, name, email, trust_score
FROM Users
WHERE trust_score < 90
ORDER BY trust_score ASC;

-- 5. List items combined with their average review rating
SELECT i.item_id, i.title,
       AVG(r.rating) AS avg_rating,
       COUNT(DISTINCT r.review_id) AS total_reviews
FROM Items i
LEFT JOIN Bookings b ON i.item_id = b.item_id
LEFT JOIN Reviews r ON b.booking_id = r.booking_id
GROUP BY i.item_id, i.title;

-- 6. Get user's booking history with payment status
SELECT b.booking_id, i.title, b.start_date, b.end_date,
       b.total_price, b.status AS booking_status,
       p.status AS payment_status, p.method
FROM Bookings b
JOIN Items i ON b.item_id = i.item_id
LEFT JOIN Payments p ON b.booking_id = p.booking_id
WHERE b.renter_id = 3
ORDER BY b.created_at DESC;

-- 7. Find top-rated items
SELECT i.item_id, i.title, u.name AS owner_name,
       AVG(r.rating) AS avg_rating, COUNT(r.review_id) AS review_count
FROM Items i
JOIN Users u ON i.owner_id = u.user_id
JOIN Bookings b ON i.item_id = b.item_id
JOIN Reviews r ON b.booking_id = r.booking_id
GROUP BY i.item_id, i.title, u.name
HAVING AVG(r.rating) >= 4
ORDER BY avg_rating DESC, review_count DESC;

-- 8. Check overlapping bookings for an item
SELECT *
FROM Bookings
WHERE item_id = 1
  AND status IN ('APPROVED', 'PENDING')
  AND (
    (start_date BETWEEN '2024-06-01' AND '2024-06-10')
    OR (end_date BETWEEN '2024-06-01' AND '2024-06-10')
    OR ('2024-06-01' BETWEEN start_date AND end_date)
    );

-- 9. Trust score change history for a user
SELECT change_amount, reason, created_at
FROM TrustEvents
WHERE user_id = 3
ORDER BY created_at DESC
LIMIT 10;

-- 10. Pending reports
SELECT r.report_id, r.entity_type, r.entity_id,
       ru.name AS reporter_name, r.reason, r.created_at
FROM Reports r
JOIN Users ru ON r.reporter_id = ru.user_id
WHERE r.status = 'PENDING'
ORDER BY r.created_at ASC;

-- 11. Items never booked
SELECT i.item_id, i.title, i.daily_rate, u.name AS owner_name, i.created_at
FROM Items i
JOIN Users u ON i.owner_id = u.user_id
LEFT JOIN Bookings b ON i.item_id = b.item_id
WHERE b.booking_id IS NULL
  AND i.status = 'AVAILABLE';

-- 12. View all Staff members and their roles
SELECT staff_id, name, email, role, status
FROM Staff
ORDER BY created_at DESC;

-- 13. View all active/open disputes and their related booking info
SELECT d.dispute_id, d.status AS dispute_status, d.reason,
       b.booking_id, u.name AS raised_by_name, d.created_at
FROM Disputes d
JOIN Bookings b ON d.booking_id = b.booking_id
JOIN Users u ON d.raised_by = u.user_id
WHERE d.status IN ('OPEN', 'UNDER_REVIEW')
ORDER BY d.created_at ASC;

-- 14. View penalties assigned to a user
SELECT p.penalty_id, p.amount, p.reason, p.status,
       u.name AS user_name, s.name AS issued_by_staff
FROM Penalties p
JOIN Users u ON p.user_id = u.user_id
JOIN Staff s ON p.issued_by = s.staff_id
WHERE u.student_id = 'S1002';

-- 15. View audit logs
SELECT audit_id, actor_type, actor_id, action_type, entity_type, entity_id, outcome, details, created_at
FROM AuditLogs
ORDER BY created_at DESC;

-- 16. Find blocked items
SELECT i.item_id, i.title, i.status, u.name AS owner_name
FROM Items i
JOIN Users u ON i.owner_id = u.user_id
WHERE i.status = 'BLOCKED';